### PR TITLE
crypto: Add nrf_cc3xx v0.9.5

### PR DESCRIPTION
**Pull request by frkv**
-Adds correct TRNG characterization values for nRF5340

ref: NCSDK-6890

manifest pr: https://github.com/nrfconnect/sdk-nrf/pull/3404

Signed-off-by: Frank Audun Kvamtrø <frank.kvamtro@nordicsemi.no>

### CODE REVIEW

**Review by tejlmand — APPROVED** [review]

**Review by torsteingrindvik — APPROVED** [review]
LGTM

**Comment by thst-nordic** [comment]
the device tree error is because of the upmerge.  we don't have a solution for how to test dtc yet.

**Comment by b-gent** [comment]
I just went on and added a small doc commit that should be squashed before merging.

Most edits were nits but there was also one colon missing which prevented the note from being shown.

Please remember to add me to PRs that include changelogs in the future.

**Review by b-gent — APPROVED** [review]

**Comment by ioannisg** [comment]
This has a passing CI in sdk-nrf.

**Pull request merged**
