### PR TITLE
bsdlib: version 0.7.4

### PR DESCRIPTION
**Pull request by peho-nordic**
Library version: 06589c1edc91a80f3835a9bfe7166a048d492564

- New socket options SILENCE_ALL, SILENCE_IP_ECHO_REPLY, SILENCE_IPV6_ECHO_REPLY and REUSEADDR
- Fix to fidoless trace disable

Signed-off-by: Petri Honkala <petri.honkala@nordicsemi.no>

sdk-nrf PR: https://github.com/nrfconnect/sdk-nrf/pull/2540
sdk-zephyr PR: https://github.com/nrfconnect/sdk-zephyr/pull/325

### CODE REVIEW

**Comment by peho-nordic** [comment]
I will open PR to `sdk-nrf` soon.

**Comment by evenl** [comment]
I just created a pr for bsdlib 0.7.5, I suggest that we close this PR and pull changes and dependencies into that PR.

**Comment by rlubos** [comment]
@evenl @peho-nordic Nothing against it, just please update the changelog file in the other one with 0.7.4 changes.

**Comment by evenl** [comment]
PR #219 is now updated to include also the changelog from this PR.

**Comment by peho-nordic** [comment]
Thanks @evenl!

**Pull request closed without merging**
