### PR TITLE
Update and improve mpsl figures

### PR DESCRIPTION
**Pull request by Avalei**
ref: NCSDK-12311

Update figures to use brand-approved colors, styles, and sizes.

Signed-off-by: Deidre Casey <deidre.casey@nordicsemi.no>

### CODE REVIEW

**Review by FrancescoSer — APPROVED** [review]

**Comment by rugeGerritsen** [comment]
@Avalei , can you add a manifest update PR so that I can take a look at the generated docs?

**Comment by Avalei** [comment]
@rugeGerritsen Here you go: https://github.com/nrfconnect/sdk-nrf/pull/6229

**Comment by rugeGerritsen** [comment]
Looks like there is something wrong in the inclusion of some of the figures:
image

**Comment by Avalei** [comment]
> Looks like there is something wrong in the inclusion of some of the figures: image
> 
> Ah, yes, the .rst files will need to be updated. All figures should be .svg and not .png so I will update those accordingly.

From what I could see, mpsl_coex_1wire_timing_grant.png was the only figure affected by the svg change. This has been updated in the .rst file and you should see it displaying correctly in the manifest update PR. Can you confirm that you do not see any other broken image links?

**Review by rugeGerritsen — APPROVED** [review]

**Comment by nvlsianpu** [comment]
A manifest PR is missing.

**Comment by nvlsianpu** [comment]
labeled `CI-disable` as nrfxlib update contains only documentation patch?

**Comment by Avalei** [comment]
Manifest PR can be found here: https://github.com/nrfconnect/sdk-nrf/pull/6229

**Pull request merged**
