### PR TITLE
doc: Update License

### PR DESCRIPTION
**Pull request by Wild8ill**
This is a cleanup change, moving forward touched
files are checked in the CI for all PR's.
Signed-off-by: William Hamshaw <William.Hamshaw@nordicsemi.no>

### CODE REVIEW

**Review by edmont — CHANGES_REQUESTED** [review]
Hi, can you please fix all the occurrences of this line?
` * SPDX-License-Identifier: LicenseRef-LicenseRef-BSD-5-Clause-Nordic-Clause-Nordic`

Also I'd like to ask you the favor to add an `openthread/license.txt` file with the following content:
```

/*
 *  Copyright (c) 2020, The OpenThread Authors.
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions are met:
 *  1. Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *  2. Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in the
 *     documentation and/or other materials provided with the distribution.
 *  3. Neither the name of the copyright holder nor the
 *     names of its contributors may be used to endorse or promote products
 *     derived from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 *  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 *  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 *  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 *  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 *  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 *  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 *  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 *  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 *  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 */

```

**Comment by edmont** [comment]
Also please fix the Nit and Gilint issues and link to a manifest PR in sdk-nrf repo.

**Comment by edmont** [comment]
Created separated PR for OpenThread: https://github.com/nrfconnect/sdk-nrfxlib/pull/318

Please don't merge changes in `openthread/lib`.

**Comment by canisLupus1313** [comment]
@Wild8ill is this PR still valid?

**Review by frkv — CHANGES_REQUESTED** [review]
Please don't change license for anything in nrfxlib/crypto or nrfxlib/nrf_security
We don't own most of these files, and the license-change is not allowed

**Comment by frkv** [comment]
Closed as it is not valid and stale

**Pull request closed without merging**
