### PR TITLE
Upmerge 25-03-2024

### PR DESCRIPTION
**Pull request by jciupis**
HWMv2 brings updated SoC names. This commit aligns the libraries directories names to match them.

### CODE REVIEW

**Review by ankuns — APPROVED** [review]

**Comment by ankuns** [comment]
@jciupis , conflicts, recent deploy or RD changed the content of SL, so so you need to rework commit named `nrf_802154: rename libraries to match updated SoC names`

**Comment by jciupis** [comment]
Cherry-picked 38b019c7cac12f1127191facc1ac92e0b12d425a from #1278 to address https://github.com/nrfconnect/sdk-nrf/pull/14626#issuecomment-2036749543

**Review by anhmolt — APPROVED** [review]
Changes to `nrf_modem` LGTM.

**Comment by magnev** [comment]
Gazell libs are not found in compilation since they are using outdated SoC names: `nRF52840` instead of `nrf52840`

**Review by leewkb4567 — APPROVED** [review]
The Gazell samples work on nRF52 DK, nRF52833 DK, nRF52840 DK, and nRF5340 DK.

**Comment by jciupis** [comment]
@gWacey please sign the CLA for all checks to pass

**Comment by Tschet1** [comment]
approved nrf_dm part. 
The nrf_dm sample is broken, but it seems it is also broken on main.

**Review by Tschet1 — APPROVED** [review]

**Comment by hermabe** [comment]
Please rebase on main and drop the commits moving the mpsl and softdevice controller libraries. We no longer use the value of `CONFIG_SOC` to determine the library paths, so there is no need to move the libraries.

**Comment by jciupis** [comment]
@hermabe please check if the current contents of this PR meet your requirements.

**Comment by hermabe** [comment]
> @hermabe please check if the current contents of this PR meet your requirements.

Looks correct to me. No changes to mpsl and softdevice controller library paths should be needed for the upmerge since we have separate configs now. I am able to build a sample on the sdk-nrf upmerge branch.

**Pull request merged**
