### PR TITLE
openthread: libraries update to commit `gc3362bc8e`

### PR DESCRIPTION
**Pull request by edmont**
- Update OpenThread libraries up to commit `gc3362bc8e`.
- Include nRF5340 libraries as well.

KRKNWK-8616

Note: libraries will need to be updated before NCS 1.5 release but after all bugfixes are added.

### CODE REVIEW

**Review by MarekPorwisz — APPROVED** [review]

**Review by lmaciejonczyk — APPROVED** [review]

**Review by tejlmand — APPROVED** [review]
I see that number of files and size has increased significantly, compared to: https://github.com/nrfconnect/sdk-nrfxlib/pull/268#pullrequestreview-504654865

```
du . -h
...
27M     .
```
and files
```
find . -name 'lib*.a'|wc -l
90
```

**Comment by edmont** [comment]
> I see that number of files and size has increased significantly, compared to: [#268 (review)](https://github.com/nrfconnect/sdk-nrfxlib/pull/268#pullrequestreview-504654865)

@tejlmand yes, this is because libraries for nRF5340 are added.

**Comment by edmont** [comment]
Force-pushing libraries with the latest nrf_security changes.

**Review by LuDuda — APPROVED** [review]

**Comment by edmont** [comment]
Manifest CI is green now.

**Review by rlubos — APPROVED** [review]

**Pull request merged**
