### PR TITLE
openthread: Generated OT libs with increased child count

### PR DESCRIPTION
**Pull request by MarekPorwisz**
Generated libraries after fix in increase child count and ip count per
child.
Updated doc to reflect this change
Depends on:
- [ ] https://github.com/nrfconnect/sdk-zephyr/pull/375
- [ ] https://github.com/nrfconnect/sdk-nrfxlib/pull/299

Jira:
https://projecttools.nordicsemi.no/jira/browse/KRKNWK-7796

Manifest:
https://github.com/nrfconnect/sdk-nrf/pull/3139

Signed-off-by: Marek Porwisz <marek.porwisz@nordicsemi.no>

### CODE REVIEW

**Review by greg-fer — APPROVED** [review]

**Review by edmont — APPROVED** [review]

**Review by lmaciejonczyk — APPROVED** [review]

**Comment by pszkotak** [comment]
I believe this PR should integrate (or be replaced with) https://github.com/nrfconnect/sdk-nrfxlib/pull/306

**Comment by pszkotak** [comment]
nrfconnect/sdk-nrf#3139 uses #306 now.
@MarekPorwisz, should we close this one?

**Comment by MarekPorwisz** [comment]
> [nrfconnect/sdk-nrf#3139](https://github.com/nrfconnect/sdk-nrf/pull/3139) uses #306 now.
> @MarekPorwisz, should we close this one?

Lets keep it until 306 is merged

**Review by shantha-14 — APPROVED** [review]

**Comment by MarekPorwisz** [comment]
closed due to other PR integrating the changes.

**Pull request closed without merging**
