### PR TITLE
doc: Update to delta_dfu_update figure

### PR DESCRIPTION
**Pull request by divipillai**
Update to delta_dfu_update figure

### CODE REVIEW

**Review by eivindj-nordic — COMMENTED** [review]
There is no longer a need to call _shutdown after checking `MODEM_DFU_RESULT` (both cases).

**Comment by divipillai** [comment]
> There is no longer a need to call `_shutdown` after checking `MODEM_DFU_RESULT`, just `_init` (both cases).

Does this apply for Rollback flowchart also: https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrfxlib/nrf_modem/doc/delta_dfu.html#id19

**Comment by eivindj-nordic** [comment]
> > There is no longer a need to call `_shutdown` after checking `MODEM_DFU_RESULT`, just `_init` (both cases).
> 
> Does this apply for Rollback flowchart also: https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrfxlib/nrf_modem/doc/delta_dfu.html#id19

Yes

**Comment by divipillai** [comment]
> > > There is no longer a need to call `_shutdown` after checking `MODEM_DFU_RESULT`, just `_init` (both cases).
> > 
> > 
> > Does this apply for Rollback flowchart also: https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrfxlib/nrf_modem/doc/delta_dfu.html#id19
> 
> Yes

Discussed offline and these updates will be covered in a separate PR.

**Review by eivindj-nordic — APPROVED** [review]

**Review by lemrey — APPROVED** [review]
Thank you @divipillai

**Pull request merged**
