### PR TITLE
openthread: add libraries based on commit ce77ab3c

### PR DESCRIPTION
**Pull request by edmont**
Update OpenThread libraries with newest commit and remove the ones
not intended for certification.

Include nRF52840 Thread 1.2 libraries as well.

Signed-off-by: Eduardo Montoya <eduardo.montoya@nordicsemi.no>

### CODE REVIEW

**Review by canisLupus1313 — APPROVED** [review]

**Review by lmaciejonczyk — APPROVED** [review]

**Review by tejlmand — CHANGES_REQUESTED** [review]
what is the relation to: #654 ?

Is this PR dependent on #654 going in first ?
Or is this PR superseding #654.

Please describe what should be reviewed in this PR.

**Comment by edmont** [comment]
@tejlmand this PR is dependent on #654, just adding OT libraries on top of #654 commits.

**Review by tejlmand — APPROVED** [review]

**Comment by tejlmand** [comment]
`DNM` for now.
Remove `DNM` when #654 is merged.

**Review by frkv — APPROVED** [review]
Can confirm that this includes everything as-is from the #658

**Comment by shantha-14** [comment]
DNM removed as #654  got merged

**Pull request merged**
