### PR TITLE
crypto: disable builtin

### PR DESCRIPTION
**Pull request by SebastianBoe**
Draft PR. Not for review.

### CODE REVIEW

**Review by joerchan — APPROVED** [review]

**Review by frkv — APPROVED** [review]
LGTM

**Comment by tejlmand** [comment]
> Draft PR. Not for review.

and then it got approved and merged 😆

**Comment by joerchan** [comment]
@lemrey Is your PR fully rebased on top of NCS main? You would need to have the changes in PR 6686.

**Comment by lemrey** [comment]
@joerchan thanks I needed to rebase the `sdk-zephyr` PR.

**Comment by SebastianBoe** [comment]
> and then it got approved and merged laughing


@tejlmand : Sorry about that, I accidentally forgot to update the PR description.

**Pull request merged**
