### PR TITLE
checkpatch: Exclude folders that contain 3rd-party code

### PR DESCRIPTION
**Pull request by carlescufi**
Exclude folder that cannot comply with the NCS coding standards due to
them including code that is developed by 3rd-party teams or companies.

Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>

### CODE REVIEW

**Review by rugeGerritsen — APPROVED** [review]

**Review by hubertmis — APPROVED** [review]

**Review by MarekPorwisz — APPROVED** [review]
Looks good, but I wonder if this is a good idea to disable entire openthread directory. I think currently only the include sub-directory of openthread contains third party files.

**Review by utzig — APPROVED** [review]

**Review by jhn-nordic — APPROVED** [review]

**Review by nordic-hani — APPROVED** [review]

**Review by kromancer — APPROVED** [review]

**Review by grochu — APPROVED** [review]
LGTM

**Review by osaether — APPROVED** [review]
LGTM

**Review by frkv — CHANGES_REQUESTED** [review]
Add crypto and nrf_security

**Comment by tejlmand** [comment]
> Add crypto and nrf_security

@frkv Glue code should still be checked, imho:
https://github.com/nrfconnect/sdk-nrfxlib/tree/master/nrf_security/src/mbedcrypto_glue

**Review by tejlmand — APPROVED** [review]

**Comment by frkv** [comment]
> > Add crypto and nrf_security
> 
> @frkv Glue code should still be checked, imho:
> https://github.com/nrfconnect/sdk-nrfxlib/tree/master/nrf_security/src/mbedcrypto_glue

I don't want competing coding standards. We use typedefs in this code and we follow mbed TLS look-and-feel

**Comment by tejlmand** [comment]
> I don't want competing coding standards. We use typedefs in this code and we follow mbed TLS look-and-feel

that sounds reasonable.
Should there be a comment after the copyright header, or elsewhere, so that it is clear to others why this code doesn't follow normal code style.

**Review by lemrey — APPROVED** [review]

**Comment by jori-nordic** [comment]
any updates on this ? checkpatch is currently blocking me from updating softdevice controller.

**Comment by rugeGerritsen** [comment]
@carlescufi , will you be able to provide the fixes suggested by @frkv ? This PR is blocking other PRs

**Comment by carlescufi** [comment]
> Add crypto and nrf_security

Done

**Review by frkv — APPROVED** [review]

**Pull request merged**
