### PR TITLE
nrf_security: Add mbed TLS options required for session resume

### PR DESCRIPTION
**Pull request by pdunaj**
Add options required to have a faster resume without a new handshake.

Jira:NCSDK-8818

Signed-off-by: Pawel Dunaj <pawel.dunaj@nordicsemi.no>

### CODE REVIEW

**Comment by pdunaj** [comment]
Tests triggered as part of https://github.com/nrfconnect/sdk-nrf/pull/4262

**Comment by pdunaj** [comment]
rebase

**Comment by pdunaj** [comment]
Hi @frkv , @tejlmand , is the change ok?

**Review by tejlmand — APPROVED** [review]

**Comment by pdunaj** [comment]
rebase

**Comment by pdunaj** [comment]
Can we have it merged?
Due to CI state it's impossible to have everything green in one go as tests time out. This time I seem to get the crypto tests run to end and pass.
https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-4262/11/

@tejlmand @frkv

**Review by frkv — APPROVED** [review]
LGTM

**Comment by pdunaj** [comment]
And as expected the tests timed out again.

**Comment by pdunaj** [comment]
rerun of nrf master passed. zigbee timedout

**Comment by pdunaj** [comment]
rerunned zigbee test passed  (I have not noticed and started it again)

**Comment by pdunaj** [comment]
@tejlmand @frkv can we merge it now?

**Comment by frkv** [comment]
> @tejlmand @frkv can we merge it now?

I see that the CI is still red for FULL_CI. Any comment on this?
I have no problem pulling this in. I don't see that this should give any risk

**Comment by pdunaj** [comment]
Hi @frkv , I suspect it does not takes into account the reruns and overall result is the effect of the first pass only.
@thst-nordic, can you confirm?

I seriously don't want to rerun it as the effect may be that it will fail again and situation won't improve. Will have to run it again anyway when manifest is updated (correct revision is applied).

**Comment by thst-nordic** [comment]
> I suspect it does not takes into account the reruns and overall result is the effect of the first pass only.

this is correct.

**Comment by frkv** [comment]
> I seriously don't want to rerun it as the effect may be that it will fail again and situation won't improve. Will have to run it again anyway when manifest is updated (correct revision is applied).

Acceptable. Please go ahead and merge @tejlmand

**Pull request merged**
