### PR TITLE
mpsl: Kconfig: add support for 802.15.4 multiprotocol

### PR DESCRIPTION
**Pull request by jciupis**
Signed-off-by: Jedrzej Ciupis <jedrzej.ciupis@nordicsemi.no>

### CODE REVIEW

**Comment by joerchan** [comment]
@jciupis Please add a body text to your commit message. There should be a check for it, but seems it is missing for this repository.

**Comment by jciupis** [comment]
In order to avoid messing up the nrfxlib master branch, this PR should not be merged until [this upstream change](https://github.com/zephyrproject-rtos/zephyr/pull/27460) is not merged to NCS.

**Comment by joerchan** [comment]
@jciupis What, we have to revert that upstream change?

**Comment by jciupis** [comment]
The upstream change is bringing some Kconfig options that this PR relies on. We need to wait for these upstream changes to be merged to NCS. Related sdk-nrf PR shows that, as the CI build fails there, and it is expected to pass once the upstream changes are already available in NCS. Therefore we should not merge this PR to nrfxlib master, because every branch that included this commit would fail now.

**Comment by joerchan** [comment]
Ok, thank you for exlaining (and editing the text that confused me).
So do you intend to cherry-pick to NCS, or wait for the next upmerge?

**Comment by jciupis** [comment]
I'm fine with waiting for the next upmerge

**Comment by joerchan** [comment]
Required upstream changes are available, removing DNM.

**Comment by hubertmis** [comment]
@joerchan, it seems that meantime somebody created the same PR #254 . It looks this one can be closed as a duplicate.
@jciupis , can you confirm?

**Comment by joerchan** [comment]
Looks like an identical change, I suppose that is why it does not even show up as a merge-conflict. Thank you @hubertmis.
@jciupis Can you check that everything is in place and close this PR and the corresponding nrf manifest update PR?

**Comment by jciupis** [comment]
I confirm that PR #254 brought the same changes, yielding this PR obsolete

**Pull request closed without merging**
