### PR TITLE
bsdlib: doc: Adding GNSS conceptual documentation

### PR DESCRIPTION
**Pull request by evenl**
Adding GNSS documentation

Manifest update: https://github.com/nrfconnect/sdk-nrf/pull/2313

Signed-off-by: Even Falch-Larsen <even.falch-larsen@nordicsemi.no>

### CODE REVIEW

**Comment by martinportmann** [comment]
Would it be possible to add some documentation to the following GPS options:
- NRF_SO_GNSS_POWER_SAVE_MODE  (What is the difference and tradeoff of the different modes)
- NRF_SO_GNSS_FIX_RETRY (What does this mean?)

Perhaps some limitations of the current implementation would also be interesting:
- no leap seconds reported at the moment (Firmware 1.1.1 with nrfconnect 1.2)

Thanks

**Comment by evenl** [comment]
@martinportmann 
I think a more suitable place for the for the clarification of NRF_SO_GNSS_POWER_SAVE_MODE and NRF_SO_GNSS_FIX_RETRY is in the API documentation it self. But I agree, it's not clear now so that documentation should be updated.

**Comment by evenl** [comment]
@martinportmann 
> no leap seconds reported at the moment (Firmware 1.1.1 with nrfconnect 1.2)
This ended up as a pretty long hunt for what you where talking about, but then we found this post on devzone. https://devzone.nordicsemi.com/f/nordic-q-a/56735/using-gps-and-lte. I assume this is you? You can track the validity of the leap second calculation through the NRF_GNSS_PVT_FLAG_LEAP_SECOND_VALID bit in the flags struct member. But you want the number of leap seconds like in the NMEA data?

**Comment by martinportmann** [comment]
> @martinportmann
> I think a more suitable place for the for the clarification of NRF_SO_GNSS_POWER_SAVE_MODE and NRF_SO_GNSS_FIX_RETRY is in the API documentation it self. But I agree, it's not clear now so that documentation should be updated.



> @martinportmann
> 
> > no leap seconds reported at the moment (Firmware 1.1.1 with nrfconnect 1.2)
> 
> This ended up as a pretty long hunt for what you where talking about, but then we found this post on devzone. https://devzone.nordicsemi.com/f/nordic-q-a/56735/using-gps-and-lte. I assume this is you? You can track the validity of the leap second calculation through the NRF_GNSS_PVT_FLAG_LEAP_SECOND_VALID bit in the flags struct member. But you want the number of leap seconds like in the NMEA data?



> @martinportmann
> 
> > no leap seconds reported at the moment (Firmware 1.1.1 with nrfconnect 1.2)
> 
> This ended up as a pretty long hunt for what you where talking about, but then we found this post on devzone. https://devzone.nordicsemi.com/f/nordic-q-a/56735/using-gps-and-lte. I assume this is you? You can track the validity of the leap second calculation through the NRF_GNSS_PVT_FLAG_LEAP_SECOND_VALID bit in the flags struct member. But you want the number of leap seconds like in the NMEA data?

All these issues are not about documentation and do probably not belong here.

1. With the Firmware 1.1.1 I never did get the NRF_GNSS_PVT_FLAG_LEAP_SECOND_VALID.
2. I would like to know the actual leap second because I have some existing code that works internally with GPS week and TOW.

**Comment by evenl** [comment]
> With the Firmware 1.1.1 I never did get the NRF_GNSS_PVT_FLAG_LEAP_SECOND_VALID.

Tech support can help you with this issue, just register a ticket on devzone.

**Comment by b-gent** [comment]
See my comment here: https://github.com/NordicPlayground/nrfxlib/pull/163#issuecomment-625290416

**Pull request merged**
