### PR TITLE
doc: Update NRF_SOL_TLS to NRF_SOL_SECURE

### PR DESCRIPTION
**Pull request by richardmccrae-nordicsemi**
Ref. NCSDK-11304

Signed-off-by: Richard McCrae <richard.mccrae@nordicsemi.no>

### CODE REVIEW

**Review by rlubos — APPROVED** [review]
LGTM, but please open a manifest update in `sdk-nrf`.

**Review by lemrey — APPROVED** [review]
Thanks

**Comment by richardmccrae-nordicsemi** [comment]
@rlubos, sorry for the dumb question, but what do you mean by open up a manifest update in nrf-sdk?  I assumed that updating the manifest would happen after this PR was merged.

**Comment by rlubos** [comment]
We need to open a manifest PR referencing the pull request first (revision set to `pull/557/head`) so the the changes are verified by the CI. Only after the manifest PR CI is green, we can merge here.

**Comment by richardmccrae-nordicsemi** [comment]
@rlubos  https://github.com/nrfconnect/sdk-nrf/pull/5759

**Pull request merged**
