### PR TITLE
492 493 494 combined

### PR DESCRIPTION
**Pull request by tejlmand**
Combined update of:
#492 
#493 
#494

### CODE REVIEW

**Review by frkv — APPROVED** [review]
Read through everything. LGTM

**Comment by frkv** [comment]
Removing approval due to mishap making glue not work... Investigating

**Comment by tejlmand** [comment]
> Removing approval due to mishap making glue not work... Investigating

Fixed now:
https://github.com/nrfconnect/sdk-nrfxlib/compare/4a9c8c32004dc4dba0ae8a494d9f658831ff2c71..64bbf00eeaba79a87d9b1b6d0259092e86ca930b

**Comment by tejlmand** [comment]
Doc already reviewed and comments addressed here: #492 
So @b-gent please approve.

**Review by frkv — APPROVED** [review]
LGTM: Fix finally verified. Glue now builds as expected

**Pull request merged**
