### PR TITLE
478 480 481 and 483

### PR DESCRIPTION
**Pull request by ioannisg**
#478 
#480 
#481 

and #483

### CODE REVIEW

**Review by rugeGerritsen — APPROVED** [review]
I approve the cherry-picked MPSL and SDC changes

**Review by tejlmand — APPROVED** [review]

**Comment by lemrey** [comment]
I have to update the `nrf_modem` commit, do no merge as is.

**Review by umapraseeda — APPROVED** [review]
Approving changes to nrf_modem/doc/CHANGELOG.rst

**Review by oyvindronningstad — APPROVED** [review]
Approving RSA change

**Review by frkv — APPROVED** [review]
My parts: LGTM

**Comment by ioannisg** [comment]
@lemrey did you push a relevant branch to sdk-nrf?

**Comment by ioannisg** [comment]
Looks like the modem update came with an API change, but there was never a PR in sdk-nrf to the best of my knowledge

**Comment by lemrey** [comment]
I had pushed https://github.com/nrfconnect/sdk-nrf/commit/c4afc180b7f8dafa66d016f856501d59b12a1033 to the matching `sdk-nrf` PR and left a comment there, but it looks like it was rewritten and did not include my changes.

**Comment by ioannisg** [comment]
> I had pushed [nrfconnect/sdk-nrf@c4afc18](https://github.com/nrfconnect/sdk-nrf/commit/c4afc180b7f8dafa66d016f856501d59b12a1033) to the matching `sdk-nrf` PR and left a comment there, but it looks like it was rewritten and did not include my changes.

@lemrey can you review 

> I had pushed [nrfconnect/sdk-nrf@c4afc18](https://github.com/nrfconnect/sdk-nrf/commit/c4afc180b7f8dafa66d016f856501d59b12a1033) to the matching `sdk-nrf` PR and left a comment there, but it looks like it was rewritten and did not include my changes.

I see. Yup, probably we had to communicate a bit better. @lemrey i saw you approved my PR, so  I guess this is the fix you had.

**Pull request merged**
