### PR TITLE
nrf_rpc: remove NULL pointer referenece

### PR DESCRIPTION
**Pull request by tomchy**
This reverts half of the changes introduced in the following PR:
https://github.com/nrfconnect/sdk-nrfxlib/pull/1493

Ref: NCSDK-29976

### CODE REVIEW

**Comment by alxelax** [comment]
FYI @Damian-Nordic

**Review by ahasztag — CHANGES_REQUESTED** [review]
This does not seem to be enough - the SUIT update still fails, although it passed after reverting the commits which introduced the change reverted here

**Comment by alxelax** [comment]
> This does not seem to be enough - the SUIT update still fails, although it passed after reverting the commits which introduced the change reverted here

Then it should be fixed correctly, not by reverting this commit. If changes are reverted, it breaks protocol serialization functionality.

**Review by alxelax — CHANGES_REQUESTED** [review]
The cause of issue should be investigated and fixed.

**Comment by tomchy** [comment]
> The cause of issue should be investigated and fixed.

Changed back to the partial revert. We are trying to fix the order of messages by adjusting the main thread priority.

**Comment by alxelax** [comment]
Hi @tomchy, please apply this patch: https://github.com/nrfconnect/sdk-nrfxlib/commit/47fdbee5fd83ed4a650b3cce7c1552a472bc570b
This is more correct fix rather than partial reverting.

**Comment by alxelax** [comment]
Alternate PR with fix: https://github.com/nrfconnect/sdk-nrfxlib/pull/1548

**Pull request closed without merging**
